# Generated by Django 4.2.2 on 2023-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
